# nginxのsync前に実行されるジョブ
---
kind: Job
apiVersion: batch/v1
metadata:
  name: job
  namespace: argocd-test-nc
  annotations:
    # 10より前に実行する
    argocd.argoproj.io/sync-wave: "9"
    # sync policy
    argocd.argoproj.io/sync-options: ApplyOutOfSyncOnly=true
spec:
  # 適当な文字列を出力する
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["echo", "job2"]
      restartPolicy: Never
  ttlSecondsAfterFinished: 10