# nginxのsync前に実行されるジョブ
---
kind: Job
apiVersion: batch/v1
metadata:
  name: job
  namespace: argocd-test-nc
  annotations:
    argocd.argoproj.io/hook: "PreSync"
    # sync policy
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    app: job
spec:
  # 適当な文字列を出力する
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["echo", "job2"]
      restartPolicy: Never
