# nginxのsync前に実行されるジョブ
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: change-detector
        image: busybox
        command: ["/bin/sh"]
        args:
         - "-c"
         - |
           sleep 5
           echo "hello"

# nginxのsync前に実行されるジョブ
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job2
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: change-detector
        image: busybox
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            sleep 5
            echo "hello"
            
      restartPolicy: Never
  backoffLimit: 2
