# 適当なアプリケーションの設定
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-test-nc

resources:
  - nginx.yaml
  - job.yaml
  - nginx2.yaml

configMapGenerator:
- name: common-cm
  envs:
  - configs/common.env

