# nginxで適当なアプリケーションをホストする設定ファイル
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx2
  namespace: argocd-test-nc
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.6
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: common-cm

---
kind: Service
apiVersion: v1
metadata:
  name: nginx2
  namespace: argocd-test-nc
  labels:
spec:
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config2
  namespace: argocd-test-nc
  labels:
data:
  nginx.conf: |
    server {
        listen 80;
        server_name nginx.argocd-test-nc.example.com;
        location / {
            proxy_pass http://nginx;
        }
    }
